Fix required 'unit_of_measurement' field for homeassistant rest polling
Problem: Homeassistant throws an error in the logs
Error: "homeassistant.components.rest.sensor.RestSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('carbon_dioxide') it is using; expected one of ['ppm']"

Fix: Add unit_of_measurement parameter to REST sensor definition